#!/bin/bash

set -x

#
# https://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters
# grep -RHn --color=auto -P "[\x80-\xFF]" *
# LC_ALL=C grep -RHn --color=auto -P "[\x80-\xFF]" *
#
# grep -RHn --color=auto -P "[^\x00-\x7F]" *
#
grep -RHn --exclude-dir=chinese --color=auto -P "[^\x00-\x7F]" *
