#!/bin/bash

set -x

if [ ! $# -eq 1 ]; then
  echo "usage: $0 {keyword}"
  exit
fi

ps axu |grep -v -E "grep |sm " |grep -i --color=auto "$1"

ps axu |grep "$1" |grep -v -E "grep |sm " |awk '{mem+=$6} END {print mem}'
