#!/bin/bash

set -x

if [ ! $# -eq 1 ]; then
  echo "usage: $0 {keyword}"
  exit
fi

# ps axu |grep -v -E "grep|sp" |grep -i --color=auto "$1"
ps axu |grep -v -E "grep|bash.*sp" |grep -i --color=auto "$1"
