#!/bin/bash

set -e

if [ ! $# -eq 1 ]; then
  echo "usage: $0 {keyword}"
else
  file="$(which $1)"
  # sudo /usr/share/vim/vim80/macros/less.sh $file
  /usr/share/vim/vim82/macros/less.sh "$file"
fi
