#!/bin/bash

[ ! -d /root/.tx ] && mkdir /root/.tx
[ ! -d /root/.tx/bk.new ] && mkdir /root/.tx/bk.new
[ ! -d /root/.tx/bk.old ] && mkdir /root/.tx/bk.old

cd /root/.tx

if $(ls /root/.tx/bk.new/*.gpg >/dev/null 2>&1); then
  mv -f /root/.tx/bk.new/*.gpg /root/.tx/bk.old/
fi

printf "\n"

ls -lh --color=auto /root/.tx/bk.old

printf "\n"

ls -lh --color=auto /root/.tx/bk.new

printf "\n"

ls -lh --color=auto /root/.tx

printf "\n"
